export const LOAD_BEERS = 'LOAD_BEERS';
export const BEERS_LOADING = 'BEERS_LOADING';
export const BEERS_LOADED = 'BEERS_LOADED';
export const SEARCH_BEERS = 'SEARCH_BEERS';
export const SEARCHING_BEERS = 'SEARCHING_BEERS';
